platform :ios, '9.0'

target 'Graygram' do
  use_frameworks!

  pod 'Alamofire', '~> 4.3'
  pod 'ObjectMapper', '~> 2.2'
  pod 'Kingfisher', '~> 3.5'
  pod 'ManualLayout', '~> 1.3'  #view.frame.width , frame.origin.x 등등을 간단하게!!
  pod 'SnapKit', '~> 3.2'     #autolayout을 코드로!
  pod 'URLNavigator', '~> 1.1'
 
end
